[system]
compatible=jethub-j310-recovery
bootloader=custom
variant-name=recovery

statusfile=/tmp/rauc.status

[handlers]
bootloader-custom-backend=/usr/libexec/rauc-bootloader-backend

[slot.recovery.0]
device=/dev/loop0
type=raw
bootname=A

[slot.recovery.1]
device=/dev/loop1
type=raw
bootname=B
