#!/bin/sh

echo "[rcS] Mounting base filesystems..."
mount -t proc proc /proc
mount -t sysfs sys /sys
mount -t tmpfs tmpfs /tmp
mount -t tmpfs tmpfs /var
mkdir -p /var/run /var/log
ln -sf /var/run /run

echo "[rcS] Setting hostname..."
hostname -F /etc/hostname



