#!/bin/bash
# shellcheck disable=SC2045

# Skip execution during shutdown or reboot
[ "$1" = "stop" ] && exit 0

echo "[init] Setting up resolv.conf overlay"
mount -t tmpfs tmpfs /tmp
if ! [ -L /etc/resolv.conf ]; then
    rm -f /etc/resolv.conf
    ln -s /tmp/resolv.conf /etc/resolv.conf
fi

# Setup wpa_supplicant.conf

#echo "[init] Cleaning up previous WPA state..."
#rm -f /var/run/wpa_supplicant/wlan0

echo "[net] Starting WPA"
wpa_supplicant -i wlan0 -c /etc/wpa_supplicant.conf -B

echo "[net] Bringing up interfaces"
for iface in $(ls /sys/class/net); do
    case "$iface" in
        lo) continue ;;
        eth*|wlan*|wl*)
            echo "[net] Bringing up $iface"
            ip link set "$iface" up

            for i in $(seq 1 10); do
                carrier="/sys/class/net/$iface/carrier"
                [ -f "$carrier" ] && [ "$(cat "$carrier")" = "1" ] && break
                sleep 1
            done

            echo "[net] Starting DHCP for $iface"
            udhcpc -i "$iface" -q -n -b > /dev/null 2>&1

            ip=$(ip addr show "$iface" | awk '/inet / {print $2}')
            echo "[net] $iface got IP: ${ip:-<none>}"
            ;;
    esac
done

#[ -x /usr/bin/wifi_setup.sh ] && /etc/init.d/wifi_setup.sh
