#!/bin/sh
# shellcheck disable=SC2045
echo "[init] Setting up resolv.conf overlay"
mount -t tmpfs tmpfs /tmp
if ! [ -L /etc/resolv.conf ]; then
    rm -f /etc/resolv.conf
    ln -s /tmp/resolv.conf /etc/resolv.conf
fi

if [ ! -L /etc/wpa_supplicant.conf ]; then
    cp /etc/wpa_supplicant.conf /tmp/wpa_supplicant.conf
    ln -sf /tmp/wpa_supplicant.conf /etc/wpa_supplicant.conf
fi

echo "[init] Cleaning up previous WPA state..."
rm -f /var/run/wpa_supplicant/wlan0
pkill -f "wpa_supplicant.*wlan0"

echo "[net] Starting WPA"
[ -e /var/run/wpa_supplicant/wlan0 ] && rm -f /var/run/wpa_supplicant/wlan0
wpa_supplicant -i wlan0 -c /etc/wpa_supplicant.conf -B
wpa_cli -a /etc/wpa_action.sh -i wlan0 -B

echo "[net] Bringing up interfaces"
for iface in $(ls /sys/class/net); do
    case "$iface" in
        lo) continue ;;
        eth*|wlan*|wl*)
            echo "[net] Bringing up $iface"
            ip link set "$iface" up

            echo "[net] Waiting for $iface to be READY..."
            for i in $(seq 1 10); do
                carrier="/sys/class/net/$iface/carrier"
                [ -f "$carrier" ] && [ "$(cat "$carrier")" = "1" ] && break
                sleep 1
            done

            echo "[net] Starting udhcpc on $iface"
            udhcpc -i "$iface" -q -n -b &
            ;;
    esac
done

[ -x /usr/bin/wifi_setup.sh ] && /etc/init.d/wifi_setup.sh
