setenv devtype mmc
if mmc dev 0; then
  setenv devnum 0
elif mmc dev 1; then
  setenv devnum 1
else
  echo "No MMC device found"
  exit
fi

# JHaOS bootargs
setenv bootargs_jhos "zram.enabled=1 zram.num_devices=3 clk_ignore_unused usb-storage.quirks=0x2537:0x1066:u,0x2537:0x1068:u fsck.repair=yes"

# Load board vars
if test -n "${board_name}"; then setenv bootargs_jhos "${bootargs_jhos} board=${board}"; fi

if test -n "${ethaddr}"; then setenv bootargs_jhos "${bootargs_jhos} mac=${ethaddr}";
else if test -n "${mac}"; then setenv bootargs_jhos "${bootargs_jhos} mac=${mac}" ; fi
fi

if test "$board" = "jethub-j200"; then
  echo "Use JetHub D2 DT file"
  setenv fdtfile "amlogic/meson-sm1-jethome-jethub-j200.dtb"
  load ${devtype} ${devnum}:1 ${fdt_addr_r} amlogic/meson-sm1-jethome-jethub-j200.dtb
  fdt addr ${fdt_addr_r}
fi;

# Load extraargs
fileenv ${devtype} ${devnum}:1 ${ramdisk_addr_r} cmdline.txt cmdline

# JHaOS system
setenv bootargs_root "root=PARTUUID=48617373-06 ro rootwait"

setenv bootargs "${bootargs_jhos} ${bootargs_root} ${cmdline}"

echo "Loading LZMA-compressed kernel from mmc"
if load ${devtype} ${devnum}:5 0x10000000 Image.lzma; then
    echo "Image.lzma loaded successfully."

    if lzmadec 0x10000000 ${kernel_addr_r}; then
        echo "LZMA decompression successful."
    else
        echo "Error: LZMA decompression failed!"
        exit
    fi

else
    echo "Error: Failed to load Image.lzma from mmc!"
    exit
fi

printenv bootargs
echo "Starting kernel"
booti ${kernel_addr_r} - ${fdt_addr_r}

echo "Boot failed, resetting..."
reset
