sf probe

# JHaOS system
setenv bootargs_root "root=/dev/mtdblock4 ro rootwait rootfs=erofs"

setenv bootargs_console "console=tty0 console=ttyAML0,115200n8"

setenv bootargs_mtdparts "mtdparts=spi0.0:2M(uboot),64k(env),7M(kernel),-(rootfs) mtdids=nor0=spi0.0"

setenv bootargs "${bootargs_console} ${bootargs_root} ${bootargs_mtdparts}"

echo "Loading LZMA-compressed kernel from mmc"
if sf read 0x10000000 0x00210000 0x00600000; then
    echo "Image.lzma loaded successfully."

    if lzmadec 0x10000000 ${kernel_addr_r}; then
        echo "LZMA decompression successful."
    else
        echo "Error: LZMA decompression failed!"
        reset
    fi

else
    echo "Error: Failed to load Image.lzma from SPI!"
    reset
fi

printenv bootargs
echo "Starting kernel"
fdt addr ${fdtcontroladdr}
booti ${kernel_addr_r} - ${fdtcontroladdr}

echo "Boot failed, resetting..."
reset
