#!/usr/bin/env bash

GREEN='\033[1;32m'
RESET='\033[0m'
export PS1='\u@\h:\w\$ '

echo -e "${GREEN}"

. /etc/os-release

echo "Hostname : $(hostname)"
echo "Uptime   : $(uptime | cut -d',' -f1 | sed 's/^ *//')"

IP=$(ip addr show | awk '/inet / && $2 !~ /^127/ {sub("/.*", "", $2); print $2; exit}')
echo "IP       : ${IP:-<not connected>}"

echo "Firmware : ${PRETTY_NAME}"
echo "Docs     : https://jethome.com"
echo "Telegram : https://t.me/jethomeru"

echo -e "${RESET}"


